---
title: "Syllabus"
date: 2023-07-04T16:12:51-05:00
draft: false
weight: 1
toc: true
math: true
---


* Location and Times

  - Course Title: Introduction to Competitive Programming
  - Rubric: CS 491 CAP
  - CRN: 65816
  - Dates: August 21, 2023 -- December 6, 2023
  - Time: 15:30 -- 14:20
  - Location: 140 Burril Hall
  - Instructor: Mattox Beckman
  - Recommended Textbooks:
     - [[https://cpbook.org][Competitive Programming 4]]
     - [[https://link.springer.com/book/10.1007/978-3-319-72547-5][Guide to Competitive Programming]]
  - Prerequisites: CS 225.  We will use C++ for our content, but you are welcome to use a different language.
  - Office Hours: TBA

* Purpose

The purpose of this course is to prepare you to compete in ICPC-style competitive programming contests.  While this will help
you compete in the Illinois Programming League, Hacker Rank, Code Forces, or similar contests, learning this material has been shown
to help with programming assignments in other courses, and many students learn this material to become confident and skillful in coding
interviews.

* Objectives and Outcomes

Upon successfully completing this course, you will have solved over 100 programming problems.  You will have learned to
select the correct algorithm depending on the problem constraints and available time and memory resources.  You will
have learned to implement your solutions quickly and accurately, being given minimal guidance if your solution is
incorrect.  You will have learned to work on your own and in an ICPC style team of students using one computer.  And
hopefully you will have a lot of fun doing so!

* Class Structure

This is a flipped classroom.  You will be given a reading from the textbook or a short video to watch, and a sample
problem or two to solve before class.  During class the instructor will ask for student comments about the problems and
give commentary.   Afterward, there will be three or so problems as homework, but you will be given class time to start
on them.  You are encouraged to ask for help from other students during the class time!  Once every two weeks we will
release a larger problem set with a variety of problems to give you practice picking the correct algorithm to use.

* Assignments and Grading

This course is a Credit/No Credit course, but will be organized as if you were going to receive a letter grade. To get credit for the course,
you must achieve a C- or better.

There are three components to your grade: attendance, solving problems, and participating in contests or other activities.

** Attendance

Attendance is required.  Your grade will be reduced by a grade step for every three unexcused absences.  (E.g., An A-
will turn into a B if you have 6 unexcused absences.)

** Solving Problems

We will calculate the percentage of the problems you solve from the pre-class problems, the homeworks, and the bi-weekly
problem sets.  Each problem has the same weight.  This category is worth 90% of the grade.

** Participation

You are also expected to participate in a certain number of timed contests.  These can be on CodeForces (1 point) or
hosted by ICPC (2 points for a 5 hour contest).  Other contest sites may also count; ask the instructor for
pre-approval.  Other activities such as attending a guest lecture or contributing problems to the course problem pool,
or creating a Team Reference Document can also count toward this requirement.  You are expected to accumulate four
participation points.  This category is worth 10% of the grade.

* Other Things
** Students with Disabilities

To obtain disability-related academic adjustments and/or auxiliary aids, students with disabilities must contact the
course instructor as soon as possible. To insure that disability-related concerns are properly addressed from the
beginning, students with disabilities who require assistance to participate in this class should contact disability
resources and educational services ([[https://www.disability.illinois.edu/)][DRES]] and see the instructor as soon as possible. If you need accommodations for any
sort of disability, please speak to me after class, or make an appointment to see me, or see me during my office hours.
DRES provides students with academic accommodations, access, and support services. To contact DRES you may visit 1207 S.
Oak St., Champaign, call 333-4603 (v/tdd), or e-mail a message to [[mailto:disability@uiuc.edu][disability@uiuc.edu]].

** Emergency Response Recommendations

The university police have posted some [[http://police.illinois.edu/emergency/][emergency response recommendations]]. I encourage you to review this website and
the campus building [[http://police.illinois.edu/emergency-preparedness/building-emergency-action-plans/][floor plans website]] within the first 10 days of class.

Of course, since we're all online, your classroom is likely your living space.  Have you considered making a fire safety
plan with your family or roommates?

** Family Educational Rights and Privacy Act (FERPA)

Any student who has suppressed their directory information pursuant to family educational rights and privacy act (FERPA)
should self-identify to the instructor to ensure protection of the privacy of their attendance in this course. see the
[[http://registrar.illinois.edu/ferpa][FERPA]] site for more information.

** Mental Health

Diminished mental health, including significant stress, mood changes, excessive worry, substance/alcohol abuse, or
problems with eating and/or sleeping can interfere with optimal academic performance, social development, and emotional
wellbeing. The University of Illinois offers a variety of confidential services including individual and group
counseling, crisis intervention, psychiatric services, and specialized screenings at no additional cost. If you or
someone you know experiences any of the above mental health concerns, it is strongly encouraged to contact or visit any
of the University's resources provided below.  Getting help is a smart and courageous thing to do -- for yourself and
for those who care about you.

Counseling Center: 217-333-3704, 610 East John Street Champaign, IL 61820

McKinley Health Center:217-333-2700, 1109 South Lincoln Avenue, Urbana, Illinois 61801
